import { useState } from "react";
import { Download, FileText, FileJson, Loader2, CheckCircle2 } from "lucide-react";
import type { WasteItem } from "./ZeeionWasteTracker";

const fmtUsd = (v: number) => {
  if (v >= 1e12) return `$${(v / 1e12).toFixed(2)}T`;
  if (v >= 1e9) return `$${(v / 1e9).toFixed(1)}B`;
  if (v >= 1e6) return `$${(v / 1e6).toFixed(1)}M`;
  if (v >= 1e3) return `$${(v / 1e3).toFixed(1)}K`;
  return `$${v.toLocaleString()}`;
};

interface Props {
  wasteItems: WasteItem[];
  countryName: string;
}

type ExportFormat = "txt" | "json" | "markdown";

const ZeeionWasteExport = ({ wasteItems, countryName }: Props) => {
  const [exporting, setExporting] = useState<ExportFormat | null>(null);
  const [exported, setExported] = useState<ExportFormat | null>(null);

  const activeStatuses = ["identified", "under_review", "plan_created", "in_progress", "partially_resolved", "recurring"];
  const resolvedStatuses = ["fully_resolved", "verified"];

  const totalIdentified = wasteItems.reduce((s, w) => s + w.annualImpact, 0);
  const activeWaste = wasteItems.filter(w => activeStatuses.includes(w.status)).reduce((s, w) => s + w.annualImpact, 0);
  const resolvedWaste = wasteItems.filter(w => resolvedStatuses.includes(w.status)).reduce((s, w) => s + w.annualImpact, 0);
  const savingsRealized = wasteItems.filter(w => w.actualSavings).reduce((s, w) => s + (w.actualSavings || 0), 0);

  const generateTXT = (): string => {
    let c = "";
    c += "═══════════════════════════════════════════════════════════════\n";
    c += "           GOVERNMENT WASTE INTELLIGENCE REPORT\n";
    c += "═══════════════════════════════════════════════════════════════\n\n";
    c += `Country: ${countryName}\n`;
    c += `Generated: ${new Date().toISOString()}\n`;
    c += `Confidence Level: AI-generated analysis\n\n`;
    c += "───────────────────────────────────────────────────────────────\n";
    c += "EXECUTIVE SUMMARY\n";
    c += "───────────────────────────────────────────────────────────────\n\n";
    c += `Total Waste Identified:     ${fmtUsd(totalIdentified)}\n`;
    c += `Current Active Waste:       ${fmtUsd(activeWaste)}\n`;
    c += `Resolved Waste:             ${fmtUsd(resolvedWaste)}\n`;
    c += `Savings Realized:           ${fmtUsd(savingsRealized)}\n`;
    c += `Items Total:                ${wasteItems.length}\n`;
    c += `Resolution Rate:            ${wasteItems.length > 0 ? ((wasteItems.filter(w => resolvedStatuses.includes(w.status)).length / wasteItems.length) * 100).toFixed(1) : 0}%\n\n`;

    c += "───────────────────────────────────────────────────────────────\n";
    c += "DETAILED WASTE INVENTORY\n";
    c += "───────────────────────────────────────────────────────────────\n\n";

    wasteItems.sort((a, b) => b.annualImpact - a.annualImpact).forEach((item, i) => {
      c += `[${i + 1}] ${item.type.replace(/_/g, " ").toUpperCase()}\n`;
      c += `    Status: ${item.status.replace(/_/g, " ")}\n`;
      c += `    Amount: ${fmtUsd(item.annualImpact)}/year\n`;
      c += `    Severity: ${item.severity}\n`;
      c += `    Confidence: ${item.confidence}%\n`;
      c += `    Description: ${item.description}\n`;
      if (item.department) c += `    Department: ${item.department}\n`;
      if (item.evidence) c += `    Evidence: ${item.evidence}\n`;
      if (item.rootCause) c += `    Root Cause: ${item.rootCause}\n`;
      if (item.recommendation) c += `    Recommendation: ${item.recommendation}\n`;
      if (item.actualSavings) c += `    Actual Savings: ${fmtUsd(item.actualSavings)}\n`;
      c += "\n";
    });

    c += "───────────────────────────────────────────────────────────────\n";
    c += "SAVINGS OPPORTUNITIES (ACTIVE)\n";
    c += "───────────────────────────────────────────────────────────────\n\n";

    const active = wasteItems.filter(w => activeStatuses.includes(w.status));
    c += `Total Potential Savings: ${fmtUsd(active.reduce((s, w) => s + w.annualImpact, 0))}\n\n`;
    active.sort((a, b) => b.annualImpact - a.annualImpact).forEach((item, i) => {
      c += `${i + 1}. ${item.description}\n`;
      c += `   Savings: ${fmtUsd(item.annualImpact)}/year\n`;
      c += `   Severity: ${item.severity}\n`;
      c += `   Status: ${item.status.replace(/_/g, " ")}\n\n`;
    });

    c += "═══════════════════════════════════════════════════════════════\n";
    c += "END OF REPORT — Generated by Aureon AI\n";
    c += "═══════════════════════════════════════════════════════════════\n";
    return c;
  };

  const generateJSON = (): string => {
    return JSON.stringify({
      metadata: { country: countryName, generatedDate: new Date().toISOString(), generatedBy: "Aureon AI", version: "1.0" },
      executiveSummary: { totalWasteIdentified: totalIdentified, currentActiveWaste: activeWaste, resolvedWaste, savingsRealized, totalItems: wasteItems.length, resolutionRate: wasteItems.length > 0 ? (wasteItems.filter(w => resolvedStatuses.includes(w.status)).length / wasteItems.length) * 100 : 0 },
      wasteInventory: wasteItems.map(w => ({ id: w.id, type: w.type, description: w.description, annualImpact: w.annualImpact, status: w.status, severity: w.severity, confidence: w.confidence, department: w.department, evidence: w.evidence, rootCause: w.rootCause, recommendation: w.recommendation, actualSavings: w.actualSavings })),
    }, null, 2);
  };

  const generateMarkdown = (): string => {
    let c = "# Government Waste Intelligence Report\n\n";
    c += `**Country:** ${countryName}  \n`;
    c += `**Generated:** ${new Date().toLocaleDateString()}  \n`;
    c += `**Source:** Aureon AI Financial Intelligence\n\n`;
    c += "---\n\n## Executive Summary\n\n";
    c += `| Metric | Value |\n|---|---|\n`;
    c += `| Total Waste Identified | ${fmtUsd(totalIdentified)} |\n`;
    c += `| Active Waste | ${fmtUsd(activeWaste)} |\n`;
    c += `| Resolved Waste | ${fmtUsd(resolvedWaste)} |\n`;
    c += `| Savings Realized | ${fmtUsd(savingsRealized)} |\n`;
    c += `| Items | ${wasteItems.length} |\n\n`;
    c += "---\n\n## Waste Inventory\n\n";
    c += "| # | Type | Amount | Status | Severity |\n|---|---|---|---|---|\n";
    wasteItems.sort((a, b) => b.annualImpact - a.annualImpact).forEach((w, i) => {
      c += `| ${i + 1} | ${w.type.replace(/_/g, " ")} | ${fmtUsd(w.annualImpact)}/yr | ${w.status.replace(/_/g, " ")} | ${w.severity} |\n`;
    });
    c += "\n---\n\n## Detailed Findings\n\n";
    wasteItems.forEach((w, i) => {
      c += `### ${i + 1}. ${w.type.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase())}\n\n`;
      c += `- **Amount:** ${fmtUsd(w.annualImpact)}/yr\n`;
      c += `- **Status:** ${w.status.replace(/_/g, " ")}\n`;
      c += `- **Description:** ${w.description}\n`;
      if (w.evidence) c += `- **Evidence:** ${w.evidence}\n`;
      if (w.recommendation) c += `- **Recommendation:** ${w.recommendation}\n`;
      c += "\n";
    });
    return c;
  };

  const doExport = async (format: ExportFormat) => {
    setExporting(format);
    await new Promise(r => setTimeout(r, 500));

    let content: string;
    let ext: string;
    let mime: string;

    switch (format) {
      case "txt":
        content = generateTXT();
        ext = "txt";
        mime = "text/plain";
        break;
      case "json":
        content = generateJSON();
        ext = "json";
        mime = "application/json";
        break;
      case "markdown":
        content = generateMarkdown();
        ext = "md";
        mime = "text/markdown";
        break;
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${countryName.replace(/\s/g, "_")}_waste_intelligence_${new Date().toISOString().split("T")[0]}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);

    setExporting(null);
    setExported(format);
    setTimeout(() => setExported(null), 3000);
  };

  const formats: { id: ExportFormat; label: string; desc: string; icon: React.ReactNode }[] = [
    { id: "txt", label: "TXT Intelligence Report", desc: "Detailed human-readable report", icon: <FileText className="h-4 w-4" /> },
    { id: "json", label: "JSON Data", desc: "Machine-readable structured data", icon: <FileJson className="h-4 w-4" /> },
    { id: "markdown", label: "Markdown Report", desc: "Formatted report for sharing", icon: <FileText className="h-4 w-4" /> },
  ];

  return (
    <div className="rounded-2xl border border-border/[0.08] bg-foreground/[0.02] p-5">
      <div className="flex items-center gap-2 mb-4">
        <Download className="h-4 w-4 text-foreground/40" />
        <span className="text-[9px] uppercase tracking-[0.2em] text-muted-foreground/40">Export Intelligence Report</span>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        {formats.map(f => (
          <button
            key={f.id}
            onClick={() => doExport(f.id)}
            disabled={exporting !== null}
            className="text-left p-4 rounded-xl border border-border/[0.08] bg-foreground/[0.02] hover:bg-foreground/[0.04] disabled:opacity-40 transition-all group"
          >
            <div className="flex items-center gap-2 mb-2">
              <span className="text-muted-foreground/40">{f.icon}</span>
              {exporting === f.id ? (
                <Loader2 className="h-3 w-3 animate-spin text-muted-foreground/30" />
              ) : exported === f.id ? (
                <CheckCircle2 className="h-3 w-3 text-emerald-400/60" />
              ) : null}
            </div>
            <p className="text-[10px] text-foreground/60 font-light">{f.label}</p>
            <p className="text-[8px] text-muted-foreground/30 mt-0.5">{f.desc}</p>
          </button>
        ))}
      </div>
    </div>
  );
};

export default ZeeionWasteExport;
