project_id = "xpgxgzqbtrrrbtjcemci"

[functions.chat]
verify_jwt = false

[functions.suggest]
verify_jwt = false

[functions.zophiel-search]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.export-data]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.ddg-search]
verify_jwt = false

[functions.zophiel-preview]
verify_jwt = false
