// built-in patterns.
//
// these come from the shepherd and pattern forge material, integrated as
// reasoning procedures — mechanisms and workflows, never a character. every one
// carries source "built_in" so provenance is never ambiguous, and they start
// active because they are shipped and reviewed, not discovered at runtime.

import type { PatternObject } from "./types";

type Seed = Omit<PatternObject, "id" | "successCount" | "failureCount" | "contextsUsed" | "version" | "evidence">;

function seed(s: Seed): PatternObject {
  return {
    ...s,
    id: "",
    successCount: 0,
    failureCount: 0,
    contextsUsed: [],
    version: 1,
    evidence: [{ kind: "fact", note: "shipped built-in procedure" }],
  };
}

export const SEED_PATTERNS: PatternObject[] = [
  seed({
    slug: "narrative-before-implementation",
    name: "narrative before implementation",
    description: "translate the ask into a narrative model and repair the model before touching the artefact",
    domain: "general",
    abstractionLevel: "meta",
    scope: "domain",
    triggerTerms: ["build", "implement", "design", "write", "create", "feature"],
    inputs: ["the request as stated"],
    preconditions: [],
    mechanism: "a wrong mental model produces a correct-looking wrong artefact; repair the model first",
    procedure: [
      "restate the ask as actors, objects, state, goal, constraints",
      "name the flaws in that narrative: workflow, logic, security, concurrency, performance, state, interface, motion",
      "rewrite the narrative with the flaws resolved",
      "only then produce the artefact",
    ],
    constraints: ["no placeholder content", "no mock presented as real"],
    expectedOutput: "an artefact built on a repaired model",
    failureModes: [{ whenFails: "trivial asks where the narrative pass costs more than it returns" }],
    evidenceQuality: "strong",
    confidence: 0.85,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "evidence-before-hypothesis",
    name: "trace before you guess",
    description: "debugging procedure that puts observation ahead of hypothesis",
    domain: "debugging",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["bug", "broken", "error", "fails", "crash", "regression", "debug"],
    inputs: ["the symptom", "the environment"],
    preconditions: ["the failure can be observed at least once"],
    mechanism: "expected model vs observed model, then a discriminating test",
    procedure: [
      "reproduce the failure",
      "state the expected behaviour and the observed behaviour separately",
      "trace the actual data flow, control flow and timing",
      "generate competing hypotheses and rank them",
      "design a test that only one hypothesis survives",
      "fix the cause, then verify and check for regression",
    ],
    constraints: ["do not patch before the cause is identified"],
    expectedOutput: "a verified fix with a named root cause",
    failureModes: [{ whenFails: "the failure cannot be reproduced", repair: "instrument first and gather evidence over time" }],
    evidenceQuality: "strong",
    confidence: 0.85,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "smallest-sufficient-change",
    name: "smallest sufficient change",
    description: "prefer the least structural intervention that fully solves a localised problem",
    domain: "software",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["fix", "patch", "refactor", "abstraction", "cleanup"],
    inputs: ["the defect", "the surrounding architecture"],
    preconditions: ["the problem is localised"],
    mechanism: "structural intervention carries regression risk proportional to its reach",
    procedure: [
      "establish whether the problem is localised or structural",
      "if localised, change only what the defect requires",
      "introduce a new abstraction only when the same deficiency appears in three or more places",
      "state the reasoning for the size of the change",
    ],
    constraints: ["no new abstraction for a one-off fix"],
    expectedOutput: "a minimal, reviewable change",
    failureModes: [{ whenFails: "a genuinely repeated structural deficiency", repair: "consolidate deliberately, with tests first" }],
    evidenceQuality: "moderate",
    confidence: 0.7,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "corroboration-weighting",
    name: "corroboration weighting",
    description: "weigh claims by independent corroboration, not by the confidence of whoever said it first",
    domain: "research",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["verify", "source", "claim", "corroborate", "true", "evidence", "research"],
    inputs: ["a claim", "its sources"],
    preconditions: [],
    mechanism: "independence of sources is the signal; repetition of one origin is not",
    procedure: [
      "separate the claim from the source that carried it",
      "check whether additional sources are genuinely independent or downstream copies",
      "raise weight only on independent corroboration",
      "surface disagreement instead of averaging it away",
      "state what would change the conclusion",
    ],
    constraints: ["never present a single-source claim as settled"],
    expectedOutput: "claims with explicit confidence and named disagreement",
    failureModes: [{ whenFails: "domains where all reporting derives from one primary record" }],
    evidenceQuality: "strong",
    confidence: 0.8,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "unknown-is-a-state",
    name: "unknown is a valid answer",
    description: "preserve unknown rather than forcing a confident-sounding answer",
    domain: "general",
    abstractionLevel: "meta",
    scope: "domain",
    triggerTerms: ["not sure", "unknown", "maybe", "estimate", "predict", "guess"],
    inputs: ["the question", "the available evidence"],
    preconditions: [],
    mechanism: "distinguish observation, inference, estimate and assumption instead of collapsing them",
    procedure: [
      "label each part of the answer as fact, inference, estimate or assumption",
      "where evidence is insufficient, say so plainly",
      "name what would resolve the unknown",
    ],
    constraints: ["never perform certainty"],
    expectedOutput: "an answer with its uncertainty intact",
    failureModes: [{ whenFails: "the user needs a decision now", repair: "give the best available option and state its basis" }],
    evidenceQuality: "strong",
    confidence: 0.85,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "cross-domain-mechanism-transfer",
    name: "cross-domain mechanism transfer",
    description: "borrow the mechanism from a distant domain rather than the surface implementation",
    domain: "general",
    abstractionLevel: "meta",
    scope: "domain",
    triggerTerms: ["analogy", "similar to", "like in", "transfer", "novel", "unprecedented"],
    inputs: ["the target problem", "known mechanisms elsewhere"],
    preconditions: ["no directly applicable pattern exists"],
    mechanism: "function -> mechanism -> invariant -> abstract pattern -> target function",
    procedure: [
      "state the function the target needs performed",
      "find a domain where that function is already solved",
      "extract the mechanism and the invariant it depends on",
      "check whether that invariant holds in the target",
      "instantiate a candidate and test it before trusting it",
    ],
    constraints: ["never copy surface form without the invariant"],
    expectedOutput: "a tested candidate approach",
    failureModes: [{ whenFails: "the invariant does not hold in the target domain", repair: "abandon the analogy rather than force it" }],
    evidenceQuality: "moderate",
    confidence: 0.65,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "design-intent-before-generation",
    name: "design intent before generation",
    description: "derive purpose, audience, hierarchy and success criteria before generating any visual",
    domain: "design",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["image", "design", "logo", "layout", "illustration", "visual", "poster"],
    inputs: ["the brief"],
    preconditions: [],
    mechanism: "generation quality is set by the specification, not by the number of attempts",
    procedure: [
      "state purpose, audience and where it will be seen",
      "define composition, hierarchy and spatial grammar",
      "state materials, lighting and context",
      "write the success criteria before generating",
      "compare the result against those criteria",
    ],
    constraints: ["do not imitate a specific living artist's protected style"],
    expectedOutput: "a generated visual with stated criteria to judge it against",
    failureModes: [{ whenFails: "purely exploratory prompts where criteria are the point of the exercise" }],
    evidenceQuality: "moderate",
    confidence: 0.7,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "answer-the-question-asked",
    name: "answer the question asked",
    description: "conversation procedure — respond to the ask, do not pivot",
    domain: "teaching",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["explain", "what is", "how does", "why", "teach"],
    inputs: ["the question"],
    preconditions: [],
    mechanism: "a pivot away from the question reads as a refusal, whatever its intent",
    procedure: [
      "answer the question that was asked, first",
      "keep the answer proportional: simple question, simple answer",
      "add context only where it changes the answer",
    ],
    constraints: ["no unsolicited commentary on the person asking"],
    expectedOutput: "a direct answer",
    failureModes: [{ whenFails: "the question rests on a false premise", repair: "name the premise, then answer" }],
    evidenceQuality: "strong",
    confidence: 0.8,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "decision-under-tradeoff",
    name: "decision under trade-off",
    description: "structured comparison when the ask is a choice",
    domain: "decision",
    abstractionLevel: "operational",
    scope: "domain",
    triggerTerms: ["should i", "which", "decide", "trade-off", "options", "versus"],
    inputs: ["the options", "what the person is optimising for"],
    preconditions: [],
    mechanism: "make the objective explicit before comparing, or the comparison is arbitrary",
    procedure: [
      "state what is being optimised for and what is being traded away",
      "list the options against those criteria",
      "identify which option is reversible and which is not",
      "recommend one, and state the condition that would change the recommendation",
    ],
    constraints: [],
    expectedOutput: "a recommendation with its reversal condition",
    failureModes: [{ whenFails: "the objective is genuinely unknown", repair: "ask one question rather than guess" }],
    evidenceQuality: "moderate",
    confidence: 0.7,
    status: "active",
    source: "built_in",
  }),
  seed({
    slug: "meta-pattern-selection",
    name: "choosing between patterns",
    description: "meta-pattern: how to pick, compose or reject patterns for a task",
    domain: "general",
    abstractionLevel: "meta",
    scope: "domain",
    triggerTerms: ["approach", "strategy", "how should", "method", "process"],
    inputs: ["the task frame", "the retrieved patterns"],
    preconditions: [],
    mechanism: "fit is judged on mechanism, not on label similarity",
    procedure: [
      "compare each candidate pattern's mechanism against the task's actual structure",
      "consider at least one contrasting or failure pattern",
      "if two partially fit, compose rather than pick",
      "if none fit, say unknown and enter discovery",
      "record which pattern was applied so the outcome can be attributed",
    ],
    constraints: ["never force a pattern for the sake of using one"],
    expectedOutput: "a named approach with attribution",
    failureModes: [{ whenFails: "the registry is empty", repair: "reason from primitives and record the result as a new candidate" }],
    evidenceQuality: "strong",
    confidence: 0.8,
    status: "active",
    source: "built_in",
  }),
];

export function seedBySlug(slug: string): PatternObject | undefined {
  return SEED_PATTERNS.find((p) => p.slug === slug);
}
