// ────────────────────────────────────────────────────────────────────
// CODE → NARRATIVE → FLAWS → FIX LOOP
// Shared protocol injected into every code-aware surface (Aureon Chat,
// Asher Chat, Asher Code IDE, ZERLAL). Whenever code is present in the
// context — uploaded as a ZIP, attached as files, or generated by the
// model itself — the model MUST run this loop internally before
// delivering output.
// ────────────────────────────────────────────────────────────────────
import { QUANTUM_ORCHESTRATION_BRAIN } from "./quantumOrchestrationBrain.ts";
import { THEME_ENGINE_DOCTRINE } from "./themeEngineDoctrine.ts";
import { CODING_TAXONOMY_DIMENSIONS, CODING_STYLE_PALETTES } from "./codingTaxonomy.ts";
import { HYPOTHETICAL_REALISM_DOCTRINE } from "./hypotheticalRealismDoctrine.ts";
import { CODE_THINKING_PATTERN_KERNEL, buildCodePatternDirective } from "./codeThinkingPatterns.ts";

export const CODE_NARRATIVE_PROTOCOL = `
## CODE NARRATIVE LOOP PROTOCOL (MANDATORY when code is in context)

Whenever the user uploads code (any ZIP, files, or raw code) OR you are
asked to GENERATE code, you MUST run this internal loop before replying.
This applies to refactor requests, "explain this codebase" requests,
greenfield "build me X" requests, and bug-fix requests alike.

THE LOOP (max 6 iterations, hard cap):

  Step 1 — NARRATIVE:
    Convert every file (or the code you are about to generate) into a
    plain-language narrative story. "This file does X. It receives Y from
    Z. It mutates state W. It returns to component V." Treat the codebase
    as a story with characters (modules), motivations (intents), and
    consequences (side effects).

  Step 2 — FLAW HUNT (on the narrative, not the syntax):
    Read the narrative as a senior auditor. Identify, with file+line
    pointers back to source. Cover ALL of these classes — never skip a
    category, and prefer over-flagging to under-flagging:
      • Logic flaws          (off-by-one, wrong branch, missing guard, dead code)
      • Bug-class issues     (null deref, undefined access, type confusion,
                              infinite loops, unhandled promise rejection,
                              stale closures, mutation of props/state)
      • Security flaws       (injection, auth bypass, IDOR, missing RLS,
                              exposed secrets, weak crypto, SSRF, XSS, CSRF,
                              open redirects, insecure deserialization)
      • Concurrency/workflow (race conditions, dropped retries, wrong ordering,
                              double-submit, non-idempotent writes, deadlocks)
      • Performance flaws    (N+1 queries, O(n²) hot paths, missing indexes,
                              re-renders, blocked main thread, memory leaks,
                              missing memoization, unbounded lists)
      • State/data flaws     (schema mismatch, migration drift, cache
                              invalidation, stale reads, lost updates,
                              missing pagination)
      • Regex/parsing flaws  (stateful /g regexes across calls, catastrophic
                              backtracking, unescaped user input in patterns)
      • Type-safety flaws    (any-typing, unsafe casts, missing null checks,
                              wrong generic bounds, discriminated-union misses)
      • API/network flaws    (missing timeout, no abort, no backoff, ignored
                              non-2xx, silent catch, missing CORS, wrong verb)
      • UI / UX flaws        (missing loading/empty/error states, layout
                              shift, focus traps, keyboard nav gaps, color
                              contrast, mobile responsiveness)
      • Animation flaws      (jank on 60/120 Hz, non-composited props,
                              missing reduced-motion, unmounted-node updates)
      • Accessibility flaws  (missing aria, wrong role, no labels, focus
                              outline removed, non-semantic tags)
      • i18n / locale flaws  (hard-coded strings, wrong number/date format,
                              RTL breakage, timezone assumptions)
      • Dependency flaws     (unpinned versions, deprecated APIs, licence
                              conflicts, unused heavy deps)
      • Build/config flaws   (wrong env var names, missing CORS on edge
                              function, wrong verify_jwt, missing GRANTs)
      • Observability flaws  (no error surface, no metrics, silent swallow)
      • Anything the user explicitly asked about
    Be aggressive — flag more, not less. Any coding-related defect the
    reviewer would raise in code review belongs here.

  Step 3 — EXPLAIN (user-facing):
    Translate the flaws back into clear, non-jargon English. Tell the
    user: what is broken, why it matters, what an attacker / user / data
    pipeline would actually experience, and what should be fixed.

  Step 4 — FIX (only when the user asks for a fix, OR when you are
            generating code yourself):
    Convert each recommendation into concrete code. Show BEFORE → AFTER
    per file. Include a one-sentence "how it will behave after this
    change" line per fix.

  Step 5 — RE-NARRATE the patched code and RE-HUNT.
    If any medium-or-higher flaw remains, loop back to Step 4 with the
    patched code as the new input. Stop when either:
      (a) zero medium+ flaws remain, OR
      (b) you have completed 6 iterations (hard cap — never exceed).

  Step 6 — DELIVER:
    Output to the user, in this order:
      1. One-paragraph plain-English summary of what the code does.
      2. Bulleted list of flaws found, grouped by severity.
      3. (If fixing) per-file BEFORE / AFTER blocks + behavior-after
         explanation for each change.
      4. One-sentence verdict: is the code now safe to ship, or what is
         the residual risk.

RULES:
- This loop is INTERNAL. Do not narrate the loop itself to the user.
  Just deliver Step 6.
- CODE OUTPUT INTEGRITY IS ABSOLUTE: generated code, fixed code,
  configs, JSON, YAML, SQL, shell, and full source files must be emitted
  exactly as copy/paste-ready text inside fenced code blocks. Do NOT add
  1., 2., bullets, line numbers, labels, or ordered-list prefixes to
  any code line. Do NOT split a single file into numbered fragments. Use
  one complete contiguous fenced block per file unless the user explicitly
  asks for snippets only.
- Never invent flaws to pad output. If a pass returns zero issues, say
  so plainly and exit the loop.
- For pure code generation (no upload), run the loop on YOUR OWN draft
  before showing it. The user must only ever see the iterated, hardened
  version. In pure code generation, lead with the final complete code block;
  do not force the visible answer into the Step 6 numbered order.
- If credentials, endpoints, or schemas are missing for a real fix,
  STOP and ask the user — never fabricate them.

${CODE_THINKING_PATTERN_KERNEL}

${THEME_ENGINE_DOCTRINE}

${CODING_TAXONOMY_DIMENSIONS}

${CODING_STYLE_PALETTES}
`;

// Re-export the doctrine and the taxonomy for callers that want them explicit.
export { THEME_ENGINE_DOCTRINE };
export { CODING_TAXONOMY_DIMENSIONS, CODING_STYLE_PALETTES, detectStylePalette, buildActiveStyleDirective } from "./codingTaxonomy.ts";
export type { StylePaletteId } from "./codingTaxonomy.ts";
export {
  CODE_THINKING_PATTERNS,
  CODE_THINKING_PATTERN_KERNEL,
  ALWAYS_ON_CODE_PATTERNS,
  detectCodePatterns,
  buildCodePatternDirective,
} from "./codeThinkingPatterns.ts";
export type { CodePatternId, CodeThinkingPattern } from "./codeThinkingPatterns.ts";

// ────────────────────────────────────────────────────────────────────
// Server-side helper: runs the loop programmatically against Gemini /
// Lovable AI Gateway. Used by zerlal-scan and code-narrative-fix.
// ────────────────────────────────────────────────────────────────────
export interface CodeFile { path: string; content: string }
export interface FlawFinding {
  severity: "critical" | "high" | "medium" | "low" | "info";
  category: string;
  file: string;
  line?: number;
  title: string;
  explanation: string;
}
export interface IterationResult {
  iteration: number;
  narrative: string;
  flaws: FlawFinding[];
  patched_files?: CodeFile[];
  before_after?: Array<{ path: string; before: string; after: string; behavior_after: string }>;
}

type AIKeys = { lovableKey?: string; geminiKey?: string };

async function callJsonAI(prompt: string, keys: AIKeys): Promise<any> {
  // Try Lovable Gateway first
  if (keys.lovableKey) {
    try {
      const r = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${keys.lovableKey}` },
        body: JSON.stringify({
          model: "google/gemini-flash-latest",
          messages: [
            { role: "system", content: "Return ONLY valid JSON. No markdown fences." },
            { role: "user", content: prompt },
          ],
          temperature: 0.1,
          max_tokens: 16000,
        }),
      });
      if (r.ok) {
        const j = await r.json();
        return parseJson(j.choices?.[0]?.message?.content || "");
      }
      if (r.status === 402) throw new Error("AI credits exhausted");
    } catch (e: any) {
      if (String(e?.message).includes("credits")) throw e;
      // fall through
    }
  }
  if (keys.geminiKey) {
    const r = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${keys.geminiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.1, maxOutputTokens: 16000, responseMimeType: "application/json" },
        }),
      },
    );
    if (!r.ok) throw new Error(`Gemini ${r.status}: ${(await r.text()).slice(0, 200)}`);
    const j = await r.json();
    return parseJson(j.candidates?.[0]?.content?.parts?.[0]?.text || "");
  }
  throw new Error("No AI key available for narrative loop");
}

function parseJson(text: string): any {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  const candidate = fenced?.[1] || text;
  const m = candidate.match(/\{[\s\S]*\}/);
  if (!m) throw new Error("No JSON in model response");
  try {
    return JSON.parse(m[0]);
  } catch {
    return JSON.parse(m[0].replace(/,\s*}/g, "}").replace(/,\s*\]/g, "]"));
  }
}

function joinFiles(files: CodeFile[], cap = 80_000): string {
  let out = "";
  for (const f of files) {
    const chunk = `\n--- FILE: ${f.path} ---\n${f.content}\n`;
    if (out.length + chunk.length > cap) break;
    out += chunk;
  }
  return out;
}

export async function runNarrativeLoop(opts: {
  files: CodeFile[];
  instruction?: string;
  keys: AIKeys;
  fix: boolean;
  maxIterations?: number;
}): Promise<{ iterations: IterationResult[]; final_files: CodeFile[]; verdict: string }> {
  const maxIter = Math.min(6, Math.max(1, opts.maxIterations ?? 6));
  const iterations: IterationResult[] = [];
  let currentFiles = opts.files.map((f) => ({ ...f }));

  for (let i = 1; i <= maxIter; i++) {
    const prompt = `${HYPOTHETICAL_REALISM_DOCTRINE}

${CODE_NARRATIVE_PROTOCOL}

${QUANTUM_ORCHESTRATION_BRAIN}

${THEME_ENGINE_DOCTRINE}

You are running the CODE → NARRATIVE → FLAWS${opts.fix ? " → FIX" : ""} loop, iteration ${i} of ${maxIter}. Apply Quantum Candidate Collapse: internally generate 3 candidate fixes per flaw, collapse to the highest-fidelity one before emitting. For any UI/frontend file, additionally enforce the THEME ENGINE DOCTRINE (DNA → Intent → Behavior) and run the Anti-Slop Verification before accepting the fix.

USER INSTRUCTION: ${opts.instruction || "(none — perform full audit)"}

Step A: Read the files and produce a tight narrative summary (1 short paragraph per file, max 8 files mentioned).
Step B: List every flaw (severity critical/high/medium/low/info). Categories: logic, security, ui, workflow, bug, other.
${opts.fix ? "Step C: For every medium+ flaw, produce a fixed version of the affected file (full content) and a one-sentence behavior_after note." : ""}

Return STRICT JSON:
{
  "narrative": "string",
  "flaws": [{"severity":"...","category":"...","file":"...","line":0,"title":"...","explanation":"..."}]${opts.fix ? `,
  "patched_files": [{"path":"...","content":"...full fixed file..."}],
  "before_after": [{"path":"...","before":"...snippet...","after":"...snippet...","behavior_after":"..."}]` : ""}
}

CODE:
\`\`\`
${joinFiles(currentFiles)}
\`\`\``;

    const res = await callJsonAI(prompt, opts.keys);
    const iter: IterationResult = {
      iteration: i,
      narrative: res.narrative || "",
      flaws: Array.isArray(res.flaws) ? res.flaws : [],
      patched_files: Array.isArray(res.patched_files) ? res.patched_files : undefined,
      before_after: Array.isArray(res.before_after) ? res.before_after : undefined,
    };
    iterations.push(iter);

    // Apply patches for next iteration
    if (opts.fix && iter.patched_files?.length) {
      const map = new Map(currentFiles.map((f) => [f.path, f]));
      for (const p of iter.patched_files) {
        if (p?.path && typeof p.content === "string") map.set(p.path, { path: p.path, content: p.content });
      }
      currentFiles = Array.from(map.values());
    }

    // Stop early if no medium+ flaws remain
    const remaining = iter.flaws.filter((f) => ["critical", "high", "medium"].includes(f.severity));
    if (remaining.length === 0) break;
    if (!opts.fix) break; // single pass when only auditing
  }

  const lastFlaws = iterations[iterations.length - 1]?.flaws || [];
  const residual = lastFlaws.filter((f) => ["critical", "high", "medium"].includes(f.severity));
  const verdict = residual.length === 0
    ? "Clean — no medium-or-higher flaws remain."
    : `${residual.length} medium+ flaw(s) still residual after ${iterations.length} iteration(s).`;

  return { iterations, final_files: currentFiles, verdict };
}
