/**
 * AxrlenPredictionBody — renders an AXRLEN engine output (markdown) inside
 * a blog post, with an attribution chip so readers (and crawlers) know the
 * prediction body is generated by the AXRLEN Nexus Prime engine, not by
 * hand-written editorial copy.
 */
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

interface PredictionSource {
  slug: string;
  topic: string;
  question: string;
  generated_at: string;
  engine: string;
  markdown: string;
}

interface Props {
  source: PredictionSource;
}

const AxrlenPredictionBody = ({ source }: Props) => {
  const generatedLabel = (() => {
    try {
      return new Date(source.generated_at).toUTCString();
    } catch {
      return source.generated_at;
    }
  })();

  return (
    <section aria-label="AXRLEN engine forecast">
      <div className="mb-8 rounded-xl border border-accent/30 bg-card/40 backdrop-blur-md p-5 font-mono text-xs leading-relaxed text-muted-foreground">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-medium tracking-[0.3em] uppercase text-accent">
            ◈ Generated by AXRLEN Engine
          </span>
          <span className="text-[10px] text-muted-foreground/60">
            {generatedLabel}
          </span>
        </div>
        <div className="text-foreground/80">
          <strong className="text-foreground">Engine:</strong> {source.engine}
        </div>
        <div className="text-foreground/80 mt-1">
          <strong className="text-foreground">Forecast question:</strong> {source.question}
        </div>
      </div>

      <article
        className="
          [&_h2]:text-2xl [&_h2]:font-light [&_h2]:tracking-tight [&_h2]:text-foreground [&_h2]:mt-10 [&_h2]:mb-4
          [&_h3]:text-xl [&_h3]:font-light [&_h3]:text-foreground [&_h3]:mt-6 [&_h3]:mb-3
          [&_p]:mb-4 [&_p]:text-foreground/80 [&_p]:leading-[1.8]
          [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_ul]:mb-4
          [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:space-y-2 [&_ol]:mb-4
          [&_li]:text-foreground/80
          [&_strong]:text-foreground
          [&_table]:w-full [&_table]:border-collapse [&_table]:my-6 [&_table]:text-sm
          [&_th]:border [&_th]:border-border/40 [&_th]:bg-card/50 [&_th]:p-2 [&_th]:text-left [&_th]:font-medium [&_th]:text-foreground
          [&_td]:border [&_td]:border-border/30 [&_td]:p-2 [&_td]:text-foreground/80
          [&_hr]:my-8 [&_hr]:border-border/30
          [&_blockquote]:border-l-2 [&_blockquote]:border-accent/50 [&_blockquote]:pl-4 [&_blockquote]:italic
          [&_code]:font-mono [&_code]:text-sm [&_code]:bg-card/60 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded
        "
      >
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {source.markdown}
        </ReactMarkdown>
      </article>
    </section>
  );
};

export default AxrlenPredictionBody;
