// herbal and supplement layer. every entry carries an evidence tier, the tissue it acts on,
// and the interactions that make it unsafe alongside common medication. nothing here is a
// prescription, and a herb with thin evidence is labelled as such rather than dressed up.
import type { Finding } from "./model";

export type EvidenceTier = "clinical-trials" | "mixed" | "traditional-only";

export interface HerbDef {
  key: string;
  label: string;
  latin: string;
  territoryKeys: string[];
  /** what it is traditionally or clinically used for. */
  uses: string[];
  mechanism: string;
  evidence: EvidenceTier;
  evidenceNote: string;
  /** drug keys from medications.ts that interact. */
  interactsWith: string[];
  interactionNote?: string;
  contraindications: string[];
  typicalForm: string;
}

export const HERBS: HerbDef[] = [
  {
    key: "turmeric",
    label: "turmeric",
    latin: "curcuma longa",
    territoryKeys: ["liver", "cartilage", "colon"],
    uses: ["joint discomfort", "digestive comfort"],
    mechanism: "curcuminoids modulate nf-κb signalling; oral bioavailability is low without piperine or a lipid carrier.",
    evidence: "mixed",
    evidenceNote: "small trials show modest joint symptom benefit; effect sizes are inconsistent across preparations.",
    interactsWith: ["warfarin", "apixaban"],
    interactionNote: "mild antiplatelet effect adds to anticoagulants.",
    contraindications: ["active gallstone obstruction", "planned surgery within two weeks"],
    typicalForm: "standardised extract with a bioavailability enhancer.",
  },
  {
    key: "ginger",
    label: "ginger",
    latin: "zingiber officinale",
    territoryKeys: ["stomach", "small-intestine", "vestibular"],
    uses: ["nausea", "motion sickness", "digestive comfort"],
    mechanism: "gingerols accelerate gastric emptying and dampen vagal nausea signalling.",
    evidence: "clinical-trials",
    evidenceNote: "consistent benefit for pregnancy and postoperative nausea in randomised trials.",
    interactsWith: ["warfarin"],
    contraindications: ["active peptic ulcer"],
    typicalForm: "dried root, capsule or tea.",
  },
  {
    key: "ashwagandha",
    label: "ashwagandha",
    latin: "withania somnifera",
    territoryKeys: ["adrenal", "hypothalamus", "thyroid"],
    uses: ["stress tolerance", "sleep onset"],
    mechanism: "withanolides modulate hpa axis output; several trials show reduced evening cortisol.",
    evidence: "mixed",
    evidenceNote: "short trials show cortisol and stress-scale changes; long-term safety data is limited, and liver injury case reports exist.",
    interactsWith: ["levothyroxine", "sertraline"],
    interactionNote: "can raise thyroid hormone levels and add sedation.",
    contraindications: ["pregnancy", "autoimmune thyroid disease", "existing liver disease"],
    typicalForm: "root extract, evening dose.",
  },
  {
    key: "st-johns-wort",
    label: "st john's wort",
    latin: "hypericum perforatum",
    territoryKeys: ["liver", "brainstem", "hippocampus"],
    uses: ["low mood"],
    mechanism: "hyperforin inhibits monoamine reuptake and strongly induces cyp3a4 and p-glycoprotein in the liver.",
    evidence: "clinical-trials",
    evidenceNote: "effective for mild to moderate depression in trials — and the single most dangerous interacting herb in common use.",
    interactsWith: ["sertraline", "warfarin", "apixaban", "atorvastatin"],
    interactionNote: "induces hepatic clearance of many drugs, including contraceptives, transplant immunosuppressants and anticoagulants, and stacks serotonergically with ssris.",
    contraindications: ["any prescription medication without pharmacist review", "pregnancy"],
    typicalForm: "standardised hypericin extract.",
  },
  {
    key: "valerian",
    label: "valerian",
    latin: "valeriana officinalis",
    territoryKeys: ["brainstem", "hypothalamus"],
    uses: ["sleep onset"],
    mechanism: "valerenic acid modulates gaba-a receptor signalling.",
    evidence: "mixed",
    evidenceNote: "subjective sleep improvement in some trials, little objective change in sleep architecture.",
    interactsWith: ["gabapentin", "sertraline"],
    contraindications: ["driving after dosing", "combination with alcohol or sedatives"],
    typicalForm: "root extract taken 60 minutes before bed.",
  },
  {
    key: "chamomile",
    label: "chamomile",
    latin: "matricaria chamomilla",
    territoryKeys: ["stomach", "small-intestine", "brainstem"],
    uses: ["digestive settling", "mild anxiety"],
    mechanism: "apigenin binds benzodiazepine sites weakly; local antispasmodic effect on gut smooth muscle.",
    evidence: "mixed",
    evidenceNote: "modest anxiolytic signal in small trials.",
    interactsWith: ["warfarin"],
    contraindications: ["asteraceae allergy"],
    typicalForm: "infusion of the dried flower.",
  },
  {
    key: "peppermint",
    label: "peppermint oil",
    latin: "mentha × piperita",
    territoryKeys: ["colon", "small-intestine", "oesophagus"],
    uses: ["irritable bowel cramping"],
    mechanism: "menthol blocks calcium channels in intestinal smooth muscle, reducing spasm.",
    evidence: "clinical-trials",
    evidenceNote: "enteric-coated peppermint oil has repeatedly beaten placebo for ibs abdominal pain.",
    interactsWith: ["omeprazole"],
    interactionNote: "acid suppression can dissolve enteric coating early, causing reflux.",
    contraindications: ["hiatus hernia with reflux", "gallstone obstruction"],
    typicalForm: "enteric-coated capsule before meals.",
  },
  {
    key: "milk-thistle",
    label: "milk thistle",
    latin: "silybum marianum",
    territoryKeys: ["liver", "gallbladder"],
    uses: ["liver support"],
    mechanism: "silymarin stabilises hepatocyte membranes and raises intracellular glutathione in laboratory models.",
    evidence: "mixed",
    evidenceNote: "no convincing effect on hard liver outcomes in humans despite strong laboratory rationale.",
    interactsWith: ["atorvastatin", "warfarin"],
    contraindications: ["asteraceae allergy"],
    typicalForm: "standardised silymarin extract.",
  },
  {
    key: "hawthorn",
    label: "hawthorn",
    latin: "crataegus monogyna",
    territoryKeys: ["heart", "coronary", "peripheral-arteries"],
    uses: ["cardiac tonic in traditional use"],
    mechanism: "flavonoids show mild positive inotropic and vasodilatory activity.",
    evidence: "mixed",
    evidenceNote: "symptomatic benefit in mild heart failure trials; not a replacement for cardiac medication.",
    interactsWith: ["metoprolol", "lisinopril", "amlodipine"],
    interactionNote: "adds to blood pressure lowering.",
    contraindications: ["diagnosed heart failure without cardiology oversight"],
    typicalForm: "leaf and flower extract.",
  },
  {
    key: "ginkgo",
    label: "ginkgo",
    latin: "ginkgo biloba",
    territoryKeys: ["cerebral-arteries", "cochlea", "peripheral-arteries"],
    uses: ["circulation", "tinnitus", "memory"],
    mechanism: "terpene lactones inhibit platelet activating factor and modestly increase microvascular flow.",
    evidence: "mixed",
    evidenceNote: "large prevention trials found no cognitive protection; small tinnitus and claudication signals persist.",
    interactsWith: ["warfarin", "apixaban", "ibuprofen"],
    interactionNote: "raises bleeding risk, including intracranial bleeding in case reports.",
    contraindications: ["anticoagulation", "seizure disorder", "surgery within two weeks"],
    typicalForm: "standardised 24% flavone glycoside extract.",
  },
  {
    key: "garlic",
    label: "garlic",
    latin: "allium sativum",
    territoryKeys: ["peripheral-arteries", "coronary", "liver"],
    uses: ["blood pressure", "lipids"],
    mechanism: "allicin derivatives promote nitric oxide availability and mildly inhibit platelet aggregation.",
    evidence: "mixed",
    evidenceNote: "small but real blood pressure reductions in meta-analyses; lipid effects are marginal.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["surgery within two weeks"],
    typicalForm: "aged extract or fresh clove.",
  },
  {
    key: "echinacea",
    label: "echinacea",
    latin: "echinacea purpurea",
    territoryKeys: ["lymph-nodes", "upper-airway", "lymphatic"],
    uses: ["upper respiratory infection duration"],
    mechanism: "alkylamides modulate innate immune cell signalling.",
    evidence: "mixed",
    evidenceNote: "meta-analyses show at best a modest reduction in cold duration; preparation quality varies enormously.",
    interactsWith: ["prednisone"],
    interactionNote: "theoretical opposition to immunosuppressive therapy.",
    contraindications: ["autoimmune disease on immunosuppression", "asteraceae allergy"],
    typicalForm: "aerial part tincture at symptom onset.",
  },
  {
    key: "elderberry",
    label: "elderberry",
    latin: "sambucus nigra",
    territoryKeys: ["upper-airway", "lymphatic"],
    uses: ["cold and influenza symptoms"],
    mechanism: "anthocyanins show antiviral activity in vitro; clinical mechanism is not established.",
    evidence: "mixed",
    evidenceNote: "small trials suggest shorter symptom duration; independent replication is thin.",
    interactsWith: ["prednisone"],
    contraindications: ["raw or unripe berries are toxic"],
    typicalForm: "prepared syrup or extract.",
  },
  {
    key: "rhodiola",
    label: "rhodiola",
    latin: "rhodiola rosea",
    territoryKeys: ["adrenal", "frontal-lobe", "muscle"],
    uses: ["fatigue", "stress tolerance"],
    mechanism: "rosavins and salidroside influence monoamine turnover and cellular stress response.",
    evidence: "mixed",
    evidenceNote: "small fatigue trials are positive but methodologically weak.",
    interactsWith: ["sertraline"],
    contraindications: ["bipolar disorder", "pregnancy"],
    typicalForm: "standardised root extract, morning dose.",
  },
  {
    key: "berberine",
    label: "berberine",
    latin: "berberis vulgaris",
    territoryKeys: ["liver", "pancreas", "colon", "small-intestine"],
    uses: ["glucose regulation", "lipids"],
    mechanism: "activates ampk and alters the gut microbiome; the metabolic effect is genuinely pharmacological.",
    evidence: "clinical-trials",
    evidenceNote: "meaningful hba1c and lipid reductions in trials — which is exactly why it must not be stacked casually with diabetes medication.",
    interactsWith: ["metformin", "insulin", "atorvastatin", "warfarin"],
    interactionNote: "additive glucose lowering, and cyp3a4 inhibition raises other drug levels.",
    contraindications: ["pregnancy", "breastfeeding", "neonates"],
    typicalForm: "divided doses with meals.",
  },
  {
    key: "cinnamon",
    label: "cinnamon (cassia)",
    latin: "cinnamomum cassia",
    territoryKeys: ["liver", "pancreas"],
    uses: ["glucose regulation"],
    mechanism: "polyphenols mildly improve insulin sensitivity in some studies.",
    evidence: "mixed",
    evidenceNote: "inconsistent glucose effects; cassia contains coumarin, which is hepatotoxic at high sustained intake.",
    interactsWith: ["metformin", "warfarin"],
    contraindications: ["liver disease", "high-dose long-term use of cassia rather than ceylon"],
    typicalForm: "ceylon cinnamon preferred for regular use.",
  },
  {
    key: "saw-palmetto",
    label: "saw palmetto",
    latin: "serenoa repens",
    territoryKeys: ["prostate", "bladder"],
    uses: ["urinary symptoms of prostate enlargement"],
    mechanism: "weak 5-alpha reductase inhibition and anti-inflammatory activity in prostatic tissue.",
    evidence: "clinical-trials",
    evidenceNote: "the largest well-designed trials found no benefit over placebo, despite widespread use.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["it lowers psa, which can mask a rising trend — tell whoever orders your psa"],
    typicalForm: "lipidosterolic extract.",
  },
  {
    key: "nettle",
    label: "nettle root",
    latin: "urtica dioica",
    territoryKeys: ["prostate", "kidney", "cartilage"],
    uses: ["urinary flow", "joint discomfort"],
    mechanism: "lignans bind sex hormone binding globulin; mild diuretic activity.",
    evidence: "traditional-only",
    evidenceNote: "long traditional use, little controlled evidence.",
    interactsWith: ["furosemide", "lisinopril"],
    interactionNote: "additive diuresis and potassium shift.",
    contraindications: ["advanced kidney disease"],
    typicalForm: "root extract or infusion.",
  },
  {
    key: "dandelion",
    label: "dandelion",
    latin: "taraxacum officinale",
    territoryKeys: ["liver", "gallbladder", "kidney"],
    uses: ["bile flow", "mild diuresis"],
    mechanism: "bitter compounds stimulate bile secretion; high potassium content accompanies the diuretic effect.",
    evidence: "traditional-only",
    evidenceNote: "traditional use only; no meaningful clinical trial base.",
    interactsWith: ["furosemide", "lisinopril"],
    contraindications: ["biliary obstruction", "advanced kidney disease"],
    typicalForm: "leaf infusion or root decoction.",
  },
  {
    key: "licorice",
    label: "liquorice root",
    latin: "glycyrrhiza glabra",
    territoryKeys: ["stomach", "adrenal", "kidney", "heart"],
    uses: ["gastric mucosal comfort", "adrenal support in traditional use"],
    mechanism: "glycyrrhizin inhibits 11-beta-hsd2, producing sodium retention, potassium loss and hypertension with sustained intake.",
    evidence: "mixed",
    evidenceNote: "deglycyrrhizinated forms avoid the mineralocorticoid effect; standard liquorice does not.",
    interactsWith: ["furosemide", "prednisone", "lisinopril", "metoprolol"],
    interactionNote: "potassium depletion compounds with diuretics and steroids.",
    contraindications: ["hypertension", "heart failure", "low potassium", "pregnancy"],
    typicalForm: "deglycyrrhizinated chewable for gastric use.",
  },
  {
    key: "aloe",
    label: "aloe vera (inner leaf)",
    latin: "aloe barbadensis",
    territoryKeys: ["stomach", "colon", "skin"],
    uses: ["gastric comfort", "topical skin repair"],
    mechanism: "polysaccharides support mucosal repair; whole-leaf latex is a stimulant laxative and is a different product entirely.",
    evidence: "mixed",
    evidenceNote: "reasonable topical evidence; oral evidence is weak and latex-containing products cause electrolyte loss.",
    interactsWith: ["furosemide", "warfarin"],
    contraindications: ["pregnancy", "inflammatory bowel disease"],
    typicalForm: "inner leaf gel, latex-free.",
  },
  {
    key: "green-tea",
    label: "green tea extract",
    latin: "camellia sinensis",
    territoryKeys: ["liver", "peripheral-arteries", "colon"],
    uses: ["metabolic support", "antioxidant intake"],
    mechanism: "egcg modulates lipid handling and endothelial function.",
    evidence: "mixed",
    evidenceNote: "drinking the tea is well tolerated; concentrated egcg extracts have caused idiosyncratic liver injury.",
    interactsWith: ["warfarin", "atorvastatin"],
    contraindications: ["existing liver disease", "high-dose extract on an empty stomach"],
    typicalForm: "brewed tea preferred over concentrated extract.",
  },
  {
    key: "red-yeast-rice",
    label: "red yeast rice",
    latin: "monascus purpureus",
    territoryKeys: ["liver", "muscle", "coronary"],
    uses: ["cholesterol"],
    mechanism: "contains monacolin k, which is chemically identical to lovastatin.",
    evidence: "clinical-trials",
    evidenceNote: "it lowers ldl because it is a statin; the dose is unregulated and varies between batches.",
    interactsWith: ["atorvastatin", "warfarin"],
    interactionNote: "taking it with a prescribed statin is a double dose of the same drug class.",
    contraindications: ["existing statin therapy", "liver disease", "pregnancy"],
    typicalForm: "avoid unless a clinician is monitoring liver enzymes and ck.",
  },
  {
    key: "magnesium-glycinate",
    label: "magnesium glycinate",
    latin: "supplement",
    territoryKeys: ["muscle", "heart", "peripheral-nerve", "brainstem"],
    uses: ["muscle cramp", "sleep quality"],
    mechanism: "replaces a cation used in over 300 enzymatic reactions and in nmda channel gating.",
    evidence: "mixed",
    evidenceNote: "clear benefit when genuinely deficient; unremarkable otherwise.",
    interactsWith: ["furosemide"],
    contraindications: ["advanced kidney disease — magnesium accumulates"],
    typicalForm: "glycinate for tolerability, oxide for laxative effect.",
  },
  {
    key: "melatonin",
    label: "melatonin",
    latin: "supplement",
    territoryKeys: ["pineal", "hypothalamus", "retina"],
    uses: ["circadian phase shifting", "jet lag"],
    mechanism: "signals biological night to the suprachiasmatic nucleus; timing matters far more than dose.",
    evidence: "clinical-trials",
    evidenceNote: "strong evidence as a phase shifter, weak evidence as a sedative.",
    interactsWith: ["warfarin", "sertraline"],
    contraindications: ["driving after dosing", "pregnancy"],
    typicalForm: "low dose several hours before target sleep time.",
  },
  {
    key: "omega3-supp",
    label: "omega-3 (epa/dha)",
    latin: "supplement",
    territoryKeys: ["heart", "cerebral-cortex", "retina", "cartilage"],
    uses: ["triglycerides", "joint comfort"],
    mechanism: "epa and dha shift eicosanoid balance and membrane composition.",
    evidence: "clinical-trials",
    evidenceNote: "clear triglyceride lowering at high dose; cardiovascular outcome data is mixed by formulation.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["surgery within a week at high dose"],
    typicalForm: "epa-dominant formulation with food.",
  },
  {
    key: "probiotic",
    label: "multi-strain probiotic",
    latin: "supplement",
    territoryKeys: ["colon", "small-intestine", "lymphatic"],
    uses: ["antibiotic-associated diarrhoea", "gut comfort"],
    mechanism: "transient colonisation competes with pathogens and modulates mucosal immunity.",
    evidence: "mixed",
    evidenceNote: "strain-specific: benefits proven for one strain do not transfer to another.",
    interactsWith: ["amoxicillin", "prednisone"],
    interactionNote: "avoid live cultures during significant immunosuppression.",
    contraindications: ["severe immunosuppression", "central venous line in place"],
    typicalForm: "strain-labelled product, taken away from antibiotic doses.",
  },
  {
    key: "dong-quai",
    label: "dong quai",
    latin: "angelica sinensis",
    territoryKeys: ["liver", "peripheral-arteries"],
    uses: ["menstrual discomfort in traditional use"],
    mechanism: "coumarin derivatives with anticoagulant and photosensitising activity.",
    evidence: "traditional-only",
    evidenceNote: "no reliable controlled evidence; the interaction risk is real regardless.",
    interactsWith: ["warfarin", "apixaban"],
    contraindications: ["anticoagulation", "pregnancy"],
    typicalForm: "decoction in traditional formulas.",
  },
];

export function herbInteractionsFor(herbKeys: string[], drugKeys: string[]) {
  const out: { herb: HerbDef; drugKey: string }[] = [];
  for (const key of herbKeys) {
    const herb = HERBS.find((h) => h.key === key);
    if (!herb) continue;
    for (const drug of drugKeys) {
      if (herb.interactsWith.includes(drug)) out.push({ herb, drugKey: drug });
    }
  }
  return out;
}

export function herbFindings(herbKeys: string[]): Finding[] {
  const out: Finding[] = [];
  for (const key of herbKeys) {
    const herb = HERBS.find((h) => h.key === key);
    if (!herb) continue;
    out.push({
      id: `herb:${herb.key}`,
      layer: "herb",
      label: `${herb.label} · ${herb.evidence.replace("-", " ")}`,
      detail: herb.evidenceNote,
      mechanism: herb.mechanism,
      nextStep: herb.contraindications.length ? `avoid if: ${herb.contraindications.join("; ")}.` : "review with a pharmacist alongside your medication list.",
      territoryKeys: herb.territoryKeys,
      direction: "active",
      weight: 0.4,
      source: `herbal reference · ${herb.latin}`,
    });
  }
  return out;
}
