// spatially anchored pain interview. the person points at the body, the engine asks the
// questions a clinician would ask about that region, and reasons about which tissue class
// produces that pattern. it never names a disease and it always screens for red flags.
import type { Finding } from "./model";

export type PainQuality =
  | "burning"
  | "electric"
  | "deep-ache"
  | "sharp-movement"
  | "cramping"
  | "pressure"
  | "throbbing"
  | "stabbing"
  | "tight-band";

export type TissueClass = "nerve" | "muscle" | "joint" | "bone" | "viscera" | "vascular" | "referred" | "unclear";

export interface QualityRule {
  quality: PainQuality;
  label: string;
  tissue: TissueClass;
  reasoning: string;
}

export const QUALITY_RULES: QualityRule[] = [
  { quality: "burning", label: "burning", tissue: "nerve", reasoning: "burning that follows a strip or glove distribution is generated by the nerve itself rather than the tissue it supplies." },
  { quality: "electric", label: "electric or shooting", tissue: "nerve", reasoning: "shooting pain travelling along a line is a nerve root or trunk firing, not local tissue damage." },
  { quality: "deep-ache", label: "deep ache", tissue: "bone", reasoning: "a deep ache that is worse at night and unrelated to position points at bone or marrow rather than muscle." },
  { quality: "sharp-movement", label: "sharp on movement", tissue: "joint", reasoning: "pain that appears only through a specific arc is mechanical: joint surface, meniscus, tendon or capsule." },
  { quality: "cramping", label: "cramping or colicky", tissue: "viscera", reasoning: "waves of cramp are smooth muscle contracting against resistance — gut, ureter or biliary tree." },
  { quality: "pressure", label: "pressure or heaviness", tissue: "vascular", reasoning: "pressure and heaviness are how visceral and vascular structures report themselves; they are poorly localised by design." },
  { quality: "throbbing", label: "throbbing", tissue: "vascular", reasoning: "pulse-synchronous pain follows arterial pulsation or raised local pressure." },
  { quality: "stabbing", label: "stabbing", tissue: "muscle", reasoning: "brief stabs reproduced by palpation usually come from muscle, fascia or costal structures." },
  { quality: "tight-band", label: "tight band", tissue: "muscle", reasoning: "band-like tightness is sustained muscle tone, often postural or protective." },
];

export interface RedFlagRule {
  key: string;
  label: string;
  /** free-text answers or flags that trigger it. */
  triggers: string[];
  urgency: "urgent" | "same-day" | "prompt";
  action: string;
}

export const RED_FLAGS: RedFlagRule[] = [
  { key: "chest-radiating", label: "chest pain radiating to jaw or arm with sweating or breathlessness", triggers: ["chest-radiating"], urgency: "urgent", action: "call emergency services now. do not drive yourself." },
  { key: "thunderclap", label: "sudden worst-ever headache reaching peak within a minute", triggers: ["thunderclap"], urgency: "urgent", action: "emergency assessment now — this pattern needs imaging today." },
  { key: "cauda-equina", label: "back pain with numbness between the legs, or bladder or bowel loss", triggers: ["saddle-numbness", "bladder-loss"], urgency: "urgent", action: "emergency department now. this is a time-critical spinal presentation." },
  { key: "calf-swelling", label: "one-sided calf swelling with pain and warmth", triggers: ["calf-unilateral"], urgency: "same-day", action: "same-day assessment — a leg clot needs excluding before travel or massage." },
  { key: "sudden-vision", label: "sudden vision loss or a new curtain across vision", triggers: ["vision-loss"], urgency: "urgent", action: "emergency eye assessment now." },
  { key: "abdo-rigid", label: "severe abdominal pain with a rigid abdomen", triggers: ["abdo-rigid"], urgency: "urgent", action: "emergency assessment now; do not eat or drink until seen." },
  { key: "night-bone-pain", label: "unremitting bone pain at night with weight loss", triggers: ["night-pain", "weight-loss"], urgency: "prompt", action: "book a clinical review this week and mention both features together." },
  { key: "fever-focal", label: "focal pain with fever and feeling systemically unwell", triggers: ["fever"], urgency: "same-day", action: "same-day clinical review — infection needs locating." },
  { key: "new-neuro-deficit", label: "new weakness, facial droop or speech difficulty", triggers: ["neuro-deficit"], urgency: "urgent", action: "call emergency services now — treat as stroke until proven otherwise." },
];

export interface InterviewQuestion {
  id: string;
  prompt: string;
  type: "single" | "multi" | "scale" | "text";
  options?: { value: string; label: string; flag?: string }[];
}

export const CORE_QUESTIONS: InterviewQuestion[] = [
  {
    id: "quality",
    prompt: "what does it feel like?",
    type: "multi",
    options: QUALITY_RULES.map((q) => ({ value: q.quality, label: q.label })),
  },
  { id: "severity", prompt: "at its worst, how strong is it?", type: "scale" },
  {
    id: "onset",
    prompt: "how did it start?",
    type: "single",
    options: [
      { value: "sudden", label: "suddenly, within seconds", flag: "thunderclap" },
      { value: "hours", label: "over hours" },
      { value: "days", label: "over days or weeks" },
      { value: "months", label: "months or longer" },
    ],
  },
  {
    id: "pattern",
    prompt: "when is it worst?",
    type: "single",
    options: [
      { value: "movement", label: "on movement or load" },
      { value: "rest", label: "at rest" },
      { value: "night", label: "at night, waking me", flag: "night-pain" },
      { value: "morning", label: "first thing, easing with movement" },
      { value: "constant", label: "constant, no pattern" },
    ],
  },
  {
    id: "radiation",
    prompt: "does it travel anywhere?",
    type: "single",
    options: [
      { value: "no", label: "no, it stays put" },
      { value: "line", label: "along a line down a limb" },
      { value: "band", label: "around like a band" },
      { value: "jaw-arm", label: "to jaw, neck or arm", flag: "chest-radiating" },
    ],
  },
  {
    id: "systemic",
    prompt: "anything else alongside it?",
    type: "multi",
    options: [
      { value: "none", label: "nothing else" },
      { value: "fever", label: "fever or chills", flag: "fever" },
      { value: "weight-loss", label: "unintended weight loss", flag: "weight-loss" },
      { value: "numbness", label: "numbness or pins and needles" },
      { value: "weakness", label: "new weakness", flag: "neuro-deficit" },
      { value: "saddle-numbness", label: "numbness between the legs", flag: "saddle-numbness" },
      { value: "bladder-loss", label: "loss of bladder or bowel control", flag: "bladder-loss" },
      { value: "breathless", label: "breathlessness or sweating", flag: "chest-radiating" },
      { value: "vision-loss", label: "vision change", flag: "vision-loss" },
      { value: "calf-unilateral", label: "one calf swollen and warm", flag: "calf-unilateral" },
      { value: "abdo-rigid", label: "abdomen hard to touch", flag: "abdo-rigid" },
    ],
  },
  { id: "relief", prompt: "what makes it better?", type: "text" },
  { id: "duration", prompt: "how long has it been going on?", type: "text" },
];

export interface PainReport {
  id: string;
  /** the part clicked on the atlas, if any. */
  partId?: string;
  partName?: string;
  territoryKeys: string[];
  answers: Record<string, string | string[] | number>;
  createdAt: string;
}

function answerList(report: PainReport, id: string): string[] {
  const v = report.answers[id];
  if (Array.isArray(v)) return v as string[];
  if (typeof v === "string") return [v];
  return [];
}

export function triggeredFlags(report: PainReport): RedFlagRule[] {
  const flags = new Set<string>();
  for (const q of CORE_QUESTIONS) {
    const chosen = answerList(report, q.id);
    for (const opt of q.options ?? []) {
      if (opt.flag && chosen.includes(opt.value)) flags.add(opt.flag);
    }
  }
  const severity = Number(report.answers.severity ?? 0);
  if (severity >= 9 && answerList(report, "onset").includes("sudden")) flags.add("thunderclap");
  return RED_FLAGS.filter((r) => r.triggers.some((t) => flags.has(t)));
}

export interface PainReasoning {
  tissue: TissueClass;
  confidence: number;
  reasoning: string[];
}

export function reasonAboutPain(report: PainReport): PainReasoning {
  const qualities = answerList(report, "quality");
  const reasoning: string[] = [];
  const score = new Map<TissueClass, number>();
  for (const q of qualities) {
    const rule = QUALITY_RULES.find((r) => r.quality === q);
    if (!rule) continue;
    score.set(rule.tissue, (score.get(rule.tissue) ?? 0) + 1);
    reasoning.push(rule.reasoning);
  }
  const radiation = answerList(report, "radiation")[0];
  if (radiation === "line") {
    score.set("nerve", (score.get("nerve") ?? 0) + 1.5);
    reasoning.push("pain travelling in a line down a limb follows a nerve root distribution rather than a muscle belly.");
  }
  if (radiation === "band") {
    score.set("nerve", (score.get("nerve") ?? 0) + 0.8);
    reasoning.push("a band around the trunk follows a single dermatome, which places the origin at the nerve root.");
  }
  const pattern = answerList(report, "pattern")[0];
  if (pattern === "movement") {
    score.set("joint", (score.get("joint") ?? 0) + 1);
    reasoning.push("load dependence means the structure is mechanical — it hurts when it carries weight.");
  }
  if (pattern === "night") {
    score.set("bone", (score.get("bone") ?? 0) + 1);
    reasoning.push("night pain that is independent of position raises the priority of a bone or inflammatory cause.");
  }
  if (pattern === "morning") {
    score.set("joint", (score.get("joint") ?? 0) + 0.8);
    reasoning.push("morning stiffness easing with movement is an inflammatory rhythm rather than a degenerative one.");
  }
  if (answerList(report, "systemic").includes("numbness")) {
    score.set("nerve", (score.get("nerve") ?? 0) + 1);
    reasoning.push("sensory change alongside the pain confirms the nerve is involved, not just irritated tissue nearby.");
  }
  let best: TissueClass = "unclear";
  let bestScore = 0;
  score.forEach((v, k) => {
    if (v > bestScore) {
      bestScore = v;
      best = k;
    }
  });
  const total = [...score.values()].reduce((a, b) => a + b, 0) || 1;
  if (best === "unclear") reasoning.push("the pattern described does not separate the tissue classes; more detail or an examination is needed.");
  return { tissue: best, confidence: Math.min(0.9, bestScore / total), reasoning };
}

export function painFindings(reports: PainReport[]): Finding[] {
  const out: Finding[] = [];
  for (const report of reports) {
    const flags = triggeredFlags(report);
    const reasoning = reasonAboutPain(report);
    const severity = Number(report.answers.severity ?? 5);
    out.push({
      id: `pain:${report.id}`,
      layer: "pain",
      label: `pain · ${report.partName ?? "unlocated"}`,
      detail: `severity ${severity}/10. the pattern is most consistent with a ${reasoning.tissue === "unclear" ? "pattern that is not yet separable" : `${reasoning.tissue} source`}.`,
      mechanism: reasoning.reasoning.join(" "),
      nextStep: flags.length
        ? flags.map((f) => f.action).join(" ")
        : "track whether it changes with load, time of day and sleep for a week — that pattern is what a clinician will ask for.",
      territoryKeys: report.territoryKeys,
      direction: "elevated",
      weight: Math.max(0.3, Math.min(1, severity / 10)),
      source: "your pain report",
      redFlag: flags.length > 0,
    });
  }
  return out;
}
