// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.0.2";

// src/lib/mcp/tools/list-conversations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-conversations.ts
var list_conversations_default = defineTool({
  name: "list_conversations",
  title: "List chat conversations",
  description: "List the signed-in user's Asherin chat conversations (title, mode, pinned/archived state, timestamps). Message bodies are not returned.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum conversations to return."),
    include_archived: z.boolean().default(false).describe("Include archived conversations.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("conversations").select("id,title,mode,pinned,archived,created_at,updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit);
    if (!include_archived) query = query.eq("archived", false);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { conversations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-directive-profiles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z2 } from "npm:zod@^3.25.76";
var list_directive_profiles_default = defineTool2({
  name: "list_directive_profiles",
  title: "List directive profiles",
  description: "List the signed-in user's directive profiles (saved standing directions applied to Asherin chat turns).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Maximum profiles to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("brains").select("id,name,description,system_prompt,is_active,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-directive-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_directive_profile_default = defineTool3({
  name: "create_directive_profile",
  title: "Create a directive profile",
  description: "Create a directive profile for the signed-in user: a named set of standing directions that Asherin chat applies when the profile is active.",
  inputSchema: {
    name: z3.string().trim().min(1).max(120).describe("Short profile name."),
    directions: z3.string().trim().min(1).max(12e3).describe("The standing directions the assistant should follow."),
    description: z3.string().trim().max(500).optional().describe("Optional short summary."),
    activate: z3.boolean().default(false).describe("Make this the active profile.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, directions, description, activate }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    if (activate) {
      const { error: clearError } = await supabase.from("brains").update({ is_active: false }).eq("user_id", userId).eq("is_active", true);
      if (clearError) {
        return { content: [{ type: "text", text: clearError.message }], isError: true };
      }
    }
    const { data, error } = await supabase.from("brains").insert({
      user_id: userId,
      name,
      description: description ?? null,
      system_prompt: directions,
      is_active: activate
    }).select("id,name,description,is_active,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-saved-targets.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z4 } from "npm:zod@^3.25.76";
var list_saved_targets_default = defineTool4({
  name: "list_saved_targets",
  title: "List saved map targets",
  description: "List the signed-in user's saved geographic targets (label, coordinates, notes) used by the Asherin Eye map surfaces.",
  inputSchema: {
    limit: z4.number().int().min(1).max(200).default(50).describe("Maximum targets to return."),
    search: z4.string().trim().max(120).optional().describe("Case-insensitive label filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("asher_saved_targets").select("id,label,lat,lng,notes,created_at,updated_at").is("deleted_at", null).order("updated_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("label", `%${search.replace(/[%_]/g, "")}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { targets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-saved-target.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z5 } from "npm:zod@^3.25.76";
var create_saved_target_default = defineTool5({
  name: "create_saved_target",
  title: "Save a map target",
  description: "Save a geographic target (label, latitude, longitude, optional notes) for the signed-in user so it appears on the Asherin Eye map.",
  inputSchema: {
    label: z5.string().trim().min(1).max(160).describe("Target label."),
    lat: z5.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    lng: z5.number().min(-180).max(180).describe("Longitude in decimal degrees."),
    notes: z5.string().trim().max(2e3).optional().describe("Optional notes about the target.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ label, lat, lng, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("asher_saved_targets").insert({ user_id: ctx.getUserId(), label, lat, lng, notes: notes ?? null }).select("id,label,lat,lng,notes,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { target: data }
    };
  }
});

// src/lib/mcp/tools/list-watchlist.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z6 } from "npm:zod@^3.25.76";
var list_watchlist_default = defineTool6({
  name: "list_watchlist",
  title: "List watchlist entities",
  description: "List the signed-in user's monitored entities (type, value, alert frequency, mention count, last check time).",
  inputSchema: {
    limit: z6.number().int().min(1).max(200).default(50).describe("Maximum entries to return."),
    enabled_only: z6.boolean().default(false).describe("Only return entries with monitoring enabled.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, enabled_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("entity_watchlist").select(
      "id,entity_type,entity_value,description,enabled,alert_frequency,mention_count,last_checked_at,created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (enabled_only) query = query.eq("enabled", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { entities: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-watchlist-entity.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z7 } from "npm:zod@^3.25.76";
var add_watchlist_entity_default = defineTool7({
  name: "add_watchlist_entity",
  title: "Add a watchlist entity",
  description: "Add an entity (person, organisation, domain, location, or other identifier) to the signed-in user's monitoring watchlist.",
  inputSchema: {
    entity_type: z7.enum(["person", "organization", "domain", "location", "keyword", "other"]).describe("Kind of entity being monitored."),
    entity_value: z7.string().trim().min(1).max(300).describe("The entity identifier or name."),
    description: z7.string().trim().max(1e3).optional().describe("Why this entity is monitored."),
    alert_frequency: z7.enum(["realtime", "hourly", "daily", "weekly"]).default("daily").describe("How often alerts should be evaluated."),
    enabled: z7.boolean().default(true).describe("Whether monitoring is active.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ entity_type, entity_value, description, alert_frequency, enabled }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("entity_watchlist").insert({
      user_id: ctx.getUserId(),
      entity_type,
      entity_value,
      description: description ?? null,
      alert_frequency,
      enabled
    }).select("id,entity_type,entity_value,description,alert_frequency,enabled,created_at").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entity: data }
    };
  }
});

// src/lib/mcp/tools/search-code-snippets.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@2.0.2";
import { z as z8 } from "npm:zod@^3.25.76";
var search_code_snippets_default = defineTool8({
  name: "search_code_snippets",
  title: "Search saved code snippets",
  description: "Search the signed-in user's saved code snippets by title or content, optionally filtered by language.",
  inputSchema: {
    query: z8.string().trim().max(200).optional().describe("Text to match in title or content."),
    language: z8.string().trim().max(40).optional().describe("Filter by language, e.g. 'typescript'."),
    limit: z8.number().int().min(1).max(50).default(20).describe("Maximum snippets to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, language, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let builder = supabase.from("code_snippets").select("id,title,language,tags,content,created_at,updated_at").order("updated_at", { ascending: false }).limit(limit);
    if (language) builder = builder.eq("language", language);
    if (query) {
      const safe = query.replace(/[%_,()]/g, " ").trim();
      if (safe) builder = builder.or(`title.ilike.%${safe}%,content.ilike.%${safe}%`);
    }
    const { data, error } = await builder;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const trimmed = (data ?? []).map((row) => ({
      ...row,
      content: typeof row.content === "string" && row.content.length > 4e3 ? `${row.content.slice(0, 4e3)}
\u2026 truncated` : row.content
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(trimmed) }],
      structuredContent: { snippets: trimmed }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xpgxgzqbtrrrbtjcemci";
var mcp_default = defineMcp({
  name: "asherin",
  title: "asherin",
  version: "0.1.0",
  instructions: "Tools for Asherin. Callers act as the signed-in Asherin user: read chat conversations, read and create directive profiles, read and create saved map targets, read and add watchlist entities, and search saved code snippets. All data is scoped to that user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_conversations_default,
    list_directive_profiles_default,
    create_directive_profile_default,
    list_saved_targets_default,
    create_saved_target_default,
    list_watchlist_default,
    add_watchlist_entity_default,
    search_code_snippets_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
