
REVOKE EXECUTE ON FUNCTION public.is_asher_conv_member(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_asher_operator(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_team_member(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_team_role(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_notebook_owner(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_notebook_share(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.notebook_team_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_has_role_in_org(uuid, uuid, public.asher_role[]) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_is_org_admin(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_is_org_member(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_is_dept_admin(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_is_section_officer(uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_admin_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_asher_super_owner(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_asher_brain_contributor(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_id_by_email(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.heartbeat_intel_slot(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.release_intel_slot(uuid, boolean) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.try_acquire_intel_slot(uuid, text, integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_intel_job_user_cap() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.tg_touch_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_predictions_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.touch_ava_picks_updated_at() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_active_sessions(integer) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_page_timeline(timestamptz, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_page_analytics(timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_aureon_overview() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_module_usage(timestamptz) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_accept_invitation(text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.asher_accept_invitation(text) FROM anon;
GRANT EXECUTE ON FUNCTION public.asher_accept_invitation(text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.hoodie_vote_totals() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.hoodie_vote_totals() TO anon, authenticated;
